### PR TITLE
fix(docs): adjust readme contributors

### PR DESCRIPTION
**Pull request by brunormferreira**
- Centralize contributors badge  and make that readable.

_From:_ [ISSUE#7](https://github.com/kentcdodds/js-testing-fundamentals/issues/7)

Thanks.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Actually, could we put this below the TestingJS image?

**Comment by brunormferreira** [comment]
Of course! I'll adjust right now.

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @brunormferreira for docs

**Pull request merged**
